[general]
import = ["~/.config/alacritty/everforest.toml"]

[env]
TERM = "xterm-256color"

[window]
padding = { x = 14, y = 14 }

[font]
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
size = 11
